package InternalFrame;

import Controlador.Ctr_Cliente;
import Modelo.Cliente;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

public class NuevoCliente extends javax.swing.JInternalFrame {

    public NuevoCliente() {
        initComponents();
        this.setSize(new Dimension(400, 300));
        this.setTitle("Nuevo Cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        bnGuardar = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        Lb1_Fondo = new javax.swing.JLabel();
        txtDescripcion2 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Nuevo Cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Dirección");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, -1));

        txtNombre.setBackground(new java.awt.Color(153, 204, 255));
        txtNombre.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, -1));

        txtapellido.setBackground(new java.awt.Color(153, 204, 255));
        txtapellido.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(0, 0, 0));
        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        txtcedula.setBackground(new java.awt.Color(153, 204, 255));
        txtcedula.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtcedula.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        txtDireccion.setBackground(new java.awt.Color(153, 204, 255));
        txtDireccion.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));

        bnGuardar.setBackground(new java.awt.Color(153, 204, 255));
        bnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        bnGuardar.setText("Guardar");
        bnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnGuardarActionPerformed(evt);
            }
        });
        bnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bnGuardarKeyPressed(evt);
            }
        });
        getContentPane().add(bnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, 30));

        txtTelefono.setBackground(new java.awt.Color(153, 204, 255));
        txtTelefono.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        Lb1_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-azul-para-textura.jpg"))); // NOI18N
        getContentPane().add(Lb1_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        txtDescripcion2.setBackground(new java.awt.Color(153, 255, 255));
        txtDescripcion2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtDescripcion2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void bnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnGuardarActionPerformed
        
         Cliente cliente = new Cliente();
        Ctr_Cliente controlCiente = new Ctr_Cliente();

        if (!txtNombre.getText().isEmpty() && !txtapellido.getText().isEmpty() && !txtcedula.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Correcto");

            if (!controlCiente.existeCliente(txtcedula.getText().trim())) {
                
                cliente.setNombre(txtNombre.getText().trim());
                cliente.setApellido(txtapellido.getText().trim());
                cliente.setDni(txtcedula.getText().trim());
                cliente.setTelefono(txtTelefono.getText().trim());
                cliente.setDireccion(txtDireccion.getText().trim());
                cliente.setEstado(1);

                if (controlCiente.guardar(cliente)) {
                    JOptionPane.showMessageDialog(null, "Registro guardado");
                    txtNombre.setBackground(Color.green);
                    txtapellido.setBackground(Color.green);
                    txtcedula.setBackground(Color.green);
                    txtTelefono.setBackground(Color.green);
                    txtDireccion.setBackground(Color.green);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar");
                }

            } else {
                JOptionPane.showMessageDialog(null, "El Cliente ya esta registrado");
                txtNombre.setBackground(Color.white);
                txtapellido.setBackground(Color.white);
                txtcedula.setBackground(Color.white);
                txtTelefono.setBackground(Color.white);
                txtDireccion.setBackground(Color.white);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Completa todos los campos");
            txtNombre.setBackground(Color.red);
            txtapellido.setBackground(Color.red);
            txtcedula.setBackground(Color.red);
            txtTelefono.setBackground(Color.red);
            txtDireccion.setBackground(Color.red);
            txtNombre.setForeground(Color.white);
             txtapellido.setBackground(Color.white);
            txtcedula.setBackground(Color.white);
            txtTelefono.setBackground(Color.white);
            txtDireccion.setBackground(Color.white);
        }
        //metodo limpiar
        this.Limpiar();
    }//GEN-LAST:event_bnGuardarActionPerformed

    private void bnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bnGuardarKeyPressed
  
    }//GEN-LAST:event_bnGuardarKeyPressed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed

    }//GEN-LAST:event_txtDireccionKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lb1_Fondo;
    private javax.swing.JButton bnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDescripcion2;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        txtNombre.setText("");
        txtapellido.setText("");
        txtcedula.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        this.txtNombre.requestFocus();
    }

      
}
